// ===========================================
// 📁 responsiveConfig.js
// -------------------------------------------
// Konfigurasi responsif global untuk dashboard
// Breakpoint:
// - xs  : ≤360p
// - sm  : ≤480p
// - md  : ≤540p
// - lg  : 720p
// - laptop : 900p–1000p
// - xl  : 1080p
// - xxl : 1440p
// - 2k  : 2560×1440
// - 4k  : 3840×2160
// - 8k  : 7680×4320
// ===========================================

export const responsiveConfig = {
  // 🎚️ Skala umum
  scale: {
    xs: "scale-[0.55]",
    sm: "scale-[0.6]",
    md: "scale-[0.7]",
    lg: "scale-[0.65]",
    laptop: "scale-[0.7]",
    xl: "scale-[1]",
    xxl: "scale-[1.05]",
    "2k": "scale-[1.15]",
    "4k": "scale-[1.25]", 
    "8k": "scale-[1.5]", 
    default: "scale-100",
  },

  // 📍 Posisi tiap komponen utama
  positions: {
    clockCorner: {
      xs: "top-2 right-2",
      sm: "top-3 right-4",
      md: "top-4 right-6",
      lg: "top-6 right-8",
      laptop: "top-5 right-7",
      xl: "top-5 right-8",
      xxl: "top-6 right-10",
      "2k": "top-10 right-12", 
      "4k": "top-16 right-16", 
      "8k": "top-24 right-20", 
      default: "top-6 right-8",
    },

    weather: {
      xs: "top-2 left-2",
      sm: "top-3 left-3",
      md: "top-0 left-0",
      lg: "top-0 left-0",
      laptop: "top-1 left-1", 
      xl: "top-0 left-0",
      xxl: "top-2 left-2",
      "2k": "top-4 left-4",
      "4k": "top-8 left-8",
      "8k": "top-12 left-12",
      default: "top-0 left-0",
    },
    calendar: {
      xs: "bottom-16 right-0",
      sm: "bottom-20 right-2",
      md: "bottom-0 right-0",
      lg: "bottom-0 right-0",
      laptop: "bottom-1 right-1", 
      xl: "bottom-0 right-0",
      xxl: "bottom-4 right-4",
      "2k": "bottom-6 right-6",
      "4k": "bottom-10 right-10",
      "8k": "bottom-14 right-14",
      default: "bottom-0 right-0",
    },
    music: {
      xs: "bottom-1 left-0",
      sm: "bottom-2 left-0",
      md: "bottom-5 left-0",
      lg: "bottom-0 left-0",
      laptop: "bottom-2 left-0", 
      xl: "bottom-2 left-1",
      xxl: "bottom-4 left-2",
      "2k": "bottom-6 left-4",
      "4k": "bottom-10 left-6",
      "8k": "bottom-14 left-8",
      default: "bottom-0 left-0",
    },

    // 🆕 Tambahan komponen utama
    header: {
      xs: "top-10 left-1/2 -translate-x-1/2",
      sm: "top-12 left-1/2 -translate-x-1/2",
      md: "top-14 left-1/2 -translate-x-1/2",
      lg: "top-2 left-1/2 -translate-x-1/2",
      laptop: "top-0 left-1/2 -translate-x-1/2", 
      xl: "top-25 left-1/2 -translate-x-1/2",
      xxl: "top-30 left-1/2 -translate-x-1/2",
      "2k": "top-40 left-1/2 -translate-x-1/2",
      "4k": "top-60 left-1/2 -translate-x-1/2",
      "8k": "top-100 left-1/2 -translate-x-1/2",
      default: "top-25 left-1/2 -translate-x-1/2",
    },
    
    clockInline: {
      xs: "top-24 left-1/2 -translate-x-1/2",
      sm: "top-28 left-1/2 -translate-x-1/2",
      md: "top-80 left-1/2 -translate-x-1/2",
      lg: "top-65 left-1/2 -translate-x-1/2",
      laptop: "top-65 left-1/2 -translate-x-1/2", 
      xl: "top-100 left-1/2 -translate-x-1/2",
      xxl: "top-100 left-1/2 -translate-x-1/2",
      "2k": "top-140 left-1/2 -translate-x-1/2",
      "4k": "top-160 left-1/2 -translate-x-1/2",
      "8k": "top-240 left-1/2 -translate-x-1/2",
      default: "top-100 left-1/2 -translate-x-1/2",
    },
    searchbar: {
      xs: "top-40 left-1/2 -translate-x-1/2 w-[80%]",
      sm: "top-44 left-1/2 -translate-x-1/2 w-[85%]",
      md: "top-100 left-1/2 -translate-x-1/2 w-[90%]",
      lg: "top-85 left-1/2 -translate-x-1/2 w-[95%]",
      laptop: "top-85 left-1/2 -translate-x-1/2 w-[92%]", 
      xl: "top-125 left-1/2 -translate-x-1/2 w-[95%]",
      xxl: "top-120 left-1/2 -translate-x-1/2 w-[96%]",
      "2k": "top-185 left-1/2 -translate-x-1/2 w-[97%]",
      "4k": "top-220 left-1/2 -translate-x-1/2 w-[98%]",
      "8k": "top-320 left-1/2 -translate-x-1/2 w-[98%]",
      default: "top-125 left-1/2 -translate-x-1/2 w-[95%]",
    },
    shortcuts: {
      xs: "bottom-10 left-1/2 -translate-x-1/2",
      sm: "bottom-12 left-1/2 -translate-x-1/2",
      md: "bottom-80 left-1/2 -translate-x-1/2",
      lg: "bottom-10 left-1/2 -translate-x-1/2",
      laptop: "bottom-15 left-1/2 -translate-x-1/2", 
      xl: "bottom-45 left-1/2 -translate-x-1/2",
      xxl: "bottom-16 left-1/2 -translate-x-1/2",
      "2k": "bottom-70 left-1/2 -translate-x-1/2",
      "4k": "bottom-32 left-1/2 -translate-x-1/2",
      "8k": "bottom-48 left-1/2 -translate-x-1/2",
      default: "bottom-45 left-1/2 -translate-x-1/2",
    },

    settings: {
      xs: "bottom-2 left-2",
      sm: "bottom-3 left-3",
      md: "bottom-4 left-4",
      lg: "bottom-5 left-5",
      laptop: "bottom-6 left-6", 
      xl: "bottom-5 left-8",
      xxl: "bottom-10 left-10",
      "2k": "bottom-12 left-12",
      "4k": "bottom-16 left-16",
      "8k": "bottom-20 left-20",
      default: "bottom-5 left-5",
    },
  },

  // 🎛️ Konfigurasi Settings Button
  settingsButton: {
    padding: {
      xs: "px-2 py-1",
      sm: "px-3 py-1.5",
      md: "px-3 py-2",
      lg: "px-4 py-2",
      laptop: "px-4 py-2", 
      xl: "px-5 py-2.5",
      xxl: "px-6 py-3",
      "2k": "px-7 py-3.5",
      "4k": "px-8 py-4",
      "8k": "px-10 py-5",
      default: "px-4 py-2",
    },
    fontSize: {
      xs: "text-xs",
      sm: "text-xs",
      md: "text-[12px]",
      lg: "text-[8px]",
      laptop: "text-[9px]", 
      xl: "text-[13px]",
      xxl: "text-lg",
      "2k": "text-xl",
      "4k": "text-2xl",
      "8k": "text-3xl",
      default: "text-sm",
    },
  },

  // 🎛️ Konfigurasi Settings Modal
  settingsModal: {
    width: {
      xs: "w-[90vw]",
      sm: "w-[88vw]",
      md: "w-[80vw]",
      lg: "w-[60vw]",
      laptop: "w-[55vw]", 
      xl: "w-[50vw]",
      xxl: "w-[55vw]",
      "2k": "w-[50vw]",
      "4k": "w-[45vw]",
      "8k": "w-[40vw]",
      default: "w-[750px]",
    },
    height: {
      xs: "h-[85vh]",
      sm: "h-[80vh]",
      md: "h-[75vh]",
      lg: "h-[75vh]",
      laptop: "h-[70vh]", 
      xl: "h-[55vh]",
      xxl: "h-[52vh]",
      "2k": "h-[48vh]",
      "4k": "h-[45vh]",
      "8k": "h-[42vh]",
      default: "h-[480px]",
    },
    padding: {
      xs: "p-2",
      sm: "p-3",
      md: "p-4",
      lg: "p-5",
      laptop: "p-5", 
      xl: "p-6",
      xxl: "p-7",
      "2k": "p-8",
      "4k": "p-10",
      "8k": "p-12",
      default: "p-6",
    },
    gap: {
      xs: "gap-1.5",
      sm: "gap-2",
      md: "gap-2.5",
      lg: "gap-5",
      laptop: "gap-3", 
      xl: "gap-4",
      xxl: "gap-5",
      "2k": "gap-6",
      "4k": "gap-7",
      "8k": "gap-8",
      default: "gap-2",
    },
    tabPadding: {
      xs: "px-2 py-1",
      sm: "px-2 py-1.5",
      md: "px-3 py-2",
      lg: "px-3 py-2",
      laptop: "px-3 py-2", 
      xl: "px-4 py-2.5",
      xxl: "px-5 py-3",
      "2k": "px-6 py-3.5",
      "4k": "px-7 py-4",
      "8k": "px-9 py-5",
      default: "px-3 py-2",
    },
    fontSize: {
      xs: "text-xs",
      sm: "text-sm",
      md: "text-sm",
      lg: "text-base",
      laptop: "text-base", 
      xl: "text-lg",
      xxl: "text-xl",
      "2k": "text-2xl",
      "4k": "text-3xl",
      "8k": "text-4xl",
      default: "text-base",
    },
  },
};
